// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3245.BCubed.subsystems;

import org.usfirst.frc3245.BCubed.RobotMap;
import org.usfirst.frc3245.BCubed.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DumpTwo extends Subsystem {

    private final SpeedController d2 = RobotMap.dumpTwod2;

    @Override
    public void initDefaultCommand() {
    }
    
    public void armDump2() {
    	d2.set(.8);
    }
    
    public void retract() {
    	d2.set(-.8);
    }
    
    public void stop() {
    	d2.set(0);
    }
    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

