// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3245.BCubed.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3245.BCubed.Robot;

/**
 *
 */
public class commandDumpOneU extends Command {

    public commandDumpOneU() {

        requires(Robot.dumpOne);

    }

    @Override
    protected void initialize() {
    }

    @Override
    protected void execute() {
    	setTimeout(0.5);
    	Robot.dumpOne.retract();
    }

    @Override
    protected boolean isFinished() {
        return isTimedOut();
    }

    @Override
    protected void end() {
    	Robot.dumpOne.stop();
    }

    @Override
    protected void interrupted() {
    }
}
