// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3245.BCubed;

import org.usfirst.frc3245.BCubed.commands.*;
import org.usfirst.frc3245.BCubed.subsystems.Shooter;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
  
    public Joystick driver, operator;
    public JoystickButton opRightTrigger, opYButton, opLeftTrigger, opRightBumper, opLeftBumper;
 

    public OI() {

        operator = new Joystick(1);
        
        opLeftBumper = new JoystickButton(operator, 7);
        opLeftBumper.whenPressed(new commandDumpTwoU());
        
        opRightBumper = new JoystickButton(operator, 6);
        opRightBumper.whenPressed(new commandDumpOneU());
        
        opLeftTrigger = new JoystickButton(operator, 5);
        opLeftTrigger.whenPressed(new commandDumpTwo());
        
        opRightTrigger = new JoystickButton(operator, 8);
        opRightTrigger.whenPressed(new commandDumpOne());
       
        opYButton = new JoystickButton(operator, 4);
        opYButton.whileHeld(new Launch());
        opYButton.whenReleased(new LaunchStop());
        driver = new Joystick(0);
        


        // SmartDashboard Buttons
        SmartDashboard.putData("TankDrive", new TankDrive(.7));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriver() {
        return driver;
    }

    public Joystick getOperator() {
        return operator;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

